export const lgaMapping = {
    "Albury City Council": "ALBURY CITY",
    "Armidale Regional Council": "ARMIDALE REGIONAL",
    "Ballina Shire Council": "BALLINA",
    "Bathurst Regional Council": "BATHURST REGIONAL",
    "Bayside Council": "BAYSIDE",
    "Bega Valley Shire Council": "BEGA VALLEY",
    "Bellingen Shire Council": "BELLINGEN",
    "Berrigan Shire Council": "BERRIGAN",
    "Blacktown City Council": "BLACKTOWN",
    "Bland Shire Council": "BLAND",
    "Blayney Shire Council": "BLAYNEY",
    "Blue Mountains City Council": "BLUE MOUNTAINS",
    "Bogan Shire Council": "BOGAN",
    "Bourke Shire Council": "BOURKE",
    "Brewarrina Shire Council": "BREWARRINA",
    "Broken Hill City Council": "BROKEN HILL",
    "Burwood Council": "BURWOOD",
    "Byron Shire Council": "BYRON",
    "Cabonne Council": "CABONNE",
    "Camden Council": "CAMDEN",
    "Campbelltown City Council": "CAMPBELLTOWN",
    "Canterbury-Bankstown Council": "CANTERBURY-BANKSTOWN",
    "Central Coast Council": "CENTRAL COAST",
    "Central Darling Shire Council": "CENTRAL DARLING",
    "Cessnock City Council": "CESSNOCK",
    "City of Canada Bay Council": "CANADA BAY",
    "City of Parramatta Council": "CITY OF PARRAMATTA",
    "City of Sydney": "SYDNEY",
    "Clarence Valley Council": "CLARENCE VALLEY",
    "Cobar Shire Council": "COBAR",
    "Coffs Harbour City Council": "COFFS HARBOUR",
    "Coolamon Shire Council": "COOLAMON",
    "Coonamble Shire Council": "COONAMBLE",
    "Cootamundra-Gundagai Regional Council": "COOTAMUNDRA-GUNDAGAI REGIONAL",
    "Cowra Shire Council": "COWRA",
    "Cumberland Council": "CUMBERLAND",
    "Dubbo Regional Council": "DUBBO REGIONAL",
    "Dungog Shire Council": "DUNGOG",
    "Edward River Council": "EDWARD RIVER",
    "Eurobodalla Shire Council": "EUROBODALLA",
    "Fairfield City Council": "FAIRFIELD",
    "Federation Council": "FEDERATION",
    "Forbes Shire Council": "FORBES",
    "Georges River Council": "GEORGES RIVER",
    "Gilgandra Shire Council": "GILGANDRA",
    "Glen Innes Severn Shire Council": "GLEN INNES SEVERN",
    "Goulburn Mulwaree Council": "GOULBURN MULWAREE",
    "Greater Hume Shire Council": "GREATER HUME SHIRE",
    "Griffith City Council": "GRIFFITH",
    "Gunnedah Shire Council": "GUNNEDAH",
    "Gwydir Shire Council": "GWYDIR",
    "Hawkesbury City Council": "HAWKESBURY",
    "Hay Shire Council": "HAY",
    "Hilltops Council": "HILLTOPS",
    "Hornsby Shire Council": "HORNSBY",
    "Hunter's Hill Council": "HUNTERS HILL",
    "Inner West Council": "INNER WEST",
    "Inverell Shire Council": "INVERELL",
    "Junee Shire Council": "JUNEE",
    "Kempsey Shire Council": "KEMPSEY",
    "Kiama Municipal Council": "KIAMA",
    "Ku-ring-gai Council": "KU-RING-GAI",
    "Kyogle Council": "KYOGLE",
    "Lachlan Shire Council": "LACHLAN",
    "Lake Macquarie City Council": "LAKE MACQUARIE",
    "Lane Cove Municipal Council": "LANE COVE",
    "Leeton Shire Council": "LEETON",
    "Lismore City Council": "LISMORE",
    "Lithgow City Council": "LITHGOW CITY",
    "Liverpool City Council": "LIVERPOOL",
    "Liverpool Plains Shire Council": "LIVERPOOL PLAINS",
    "Lockhart Shire Council": "LOCKHART",
    "Maitland City Council": "MAITLAND",
    "Mid-Coast Council": "MID-COAST",
    "Mid-Western Regional Council": "MID-WESTERN REGIONAL",
    "Moree Plains Shire Council": "MOREE PLAINS",
    "Mosman Municipal Council": "MOSMAN",
    "Murray River Council": "MURRAY RIVER",
    "Murrumbidgee Council": "MURRUMBIDGEE",
    "Muswellbrook Shire Council": "MUSWELLBROOK",
    "Nambucca Valley Council": "NAMBUCCA VALLEY",
    "Narrabri Shire Council": "NARRABRI",
    "Narrandera Shire Council": "NARRANDERA",
    "Narromine Shire Council": "NARROMINE",
    "Newcastle City Council": "NEWCASTLE",
    "North Sydney Council": "NORTH SYDNEY",
    "Northern Beaches Council": "NORTHERN BEACHES",
    "Oberon Council": "OBERON",
    "Orange City Council": "ORANGE",
    "Parkes Shire Council": "PARKES",
    "Penrith City Council": "PENRITH",
    "Port Macquarie-Hastings Council": "PORT MACQUARIE-HASTINGS",
    "Port Stephens Council": "PORT STEPHENS",
    "Queanbeyan-Palerang Regional Council": "QUEANBEYAN-PALERANG REGIONAL",
    "Randwick City Council": "RANDWICK",
    "Richmond Valley Council": "RICHMOND VALLEY",
    "Ryde City Council": "RYDE",
    "Shellharbour City Council": "SHELLHARBOUR",
    "Shoalhaven City Council": "SHOALHAVEN",
    "Singleton Council": "SINGLETON",
    "Snowy Monaro Regional Council": "SNOWY MONARO REGIONAL",
    "Snowy Valleys Council": "SNOWY VALLEYS",
    "Strathfield Municipal Council": "STRATHFIELD",
    "Sutherland Shire Council": "SUTHERLAND SHIRE",
    "Tamworth Regional Council": "TAMWORTH REGIONAL",
    "Temora Shire Council": "TEMORA",
    "Tenterfield Shire Council": "TENTERFIELD",
    "The Hills Shire Council": "THE HILLS SHIRE",
    "Tweed Shire Council": "TWEED",
    "Upper Hunter Shire Council": "UPPER HUNTER",
    "Upper Lachlan Shire Council": "UPPER LACHLAN SHIRE",
    "Uralla Shire Council": "URALLA",
    "Wagga Wagga City Council": "WAGGA WAGGA",
    "Walcha Council": "WALCHA",
    "Walgett Shire Council": "WALGETT",
    "Warren Shire Council": "WARREN",
    "Warrumbungle Shire Council": "WARRUMBUNGLE",
    "Waverley Council": "WAVERLEY",
    "Weddin Shire Council": "WEDDIN",
    "Wentworth Shire Council": "WENTWORTH",
    "Willoughby City Council": "WILLOUGHBY",
    "Wingecarribee Shire Council": "WINGECARRIBEE",
    "Wollondilly Shire Council": "WOLLONDILLY",
    "Wollongong City Council": "WOLLONGONG",
    "Woollahra Municipal Council": "WOOLLAHRA",
    "Yass Valley Council": "YASS VALLEY"
  };